import { Heading, Text } from '@chakra-ui/react'
import Head from 'next/head'
import { useSelector } from 'react-redux'
import { RootState } from '../store'

export default function Home() {
  const state = useSelector((state) => state) as RootState
  return (
    <div>
      <Head>
        <title>DMG Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading>Home Page</Heading>
      <Text>Logged in user: {state.auth.name}</Text>
      <pre>{JSON.stringify(state.auth)}</pre>
    </div>
  )
}
